### ISSUE TITLE
Test just one file

### ISSUE THREAD

**Issue by LeventErkok** [phadej/cabal-extras#103]
Really like cabal-docspec. Thanks for the great program, and waiting for its Hackage release.

One question: While fixing the tests, sometimes I just want docspec to run tests that originate from just one file. Is it possible to tell docspec to skip tests coming from all the other files and just run ones from a given source file(s)?

I checked the command-line arguments, but didn't see anything suitable.

**Comment by phadej** [comment]
There isn't, but filtering by module name would indeed be handy.

**Comment by phadej** [comment]
Added a --module flag in #104

**Comment by LeventErkok** [comment]
Thanks! Just tested it, and it works great.
