### ISSUE TITLE
cabal-docspec: default extensions

### ISSUE THREAD

**Issue by nalkuatov** [phadej/cabal-extras#106]
Is it possible to enable the set of extensions, that are active during the compilation, for `cabal-docspec` by default? I suppose `plan.json` doesn't contain such info, but at least with `--no-cabal-plan`, would it be possible to read the extensions from the plan provided?

**Comment by phadej** [comment]
- https://github.com/phadej/cabal-extras/blob/master/cabal-docspec/MANUAL.md#using-ghc-extensions
- https://github.com/phadej/cabal-extras/blob/master/cabal-docspec/MANUAL.md#cabal-fields
