### ISSUE TITLE
Can you release on hackage (and stackage (and nixpkgs))? 

### ISSUE THREAD

**Issue by turion** [phadej/cabal-extras#135]
It would be great to have these tools available easily. One way would be by just releasing them on hackage and stackage. Then nixpkgs would automatically pick them up, making them available to every NixOS user.

**Comment by turion** [comment]
(I am aware of the other tickets asking for a hackage upload, but I'm nevertheless asking again: Your mind might have changed, and my main aim for asking is such that there is an easy way to install these tools via nix.)

**Comment by ulysses4ever** [comment]
Indeed, that would be great. Alternatively, maybe, an option for a community-managed Hackage release could be considered. I'm sure there're plenty of people who would be willing to help out with that.

**Comment by turion** [comment]
Or else, a `flake.nix`?

**Comment by ulysses4ever** [comment]
That could help too but having a release on Hackage would hit a much wider audience I think.

**Comment by phadej** [comment]
The previous reasons are still valid.

Especially Stackage is not going to happen. It puts even more restrictions (if we'd need to keep tools in LTS and Nightly).

Build from source, or download prebuilt binary (for `cabal-docspec`).
