### ISSUE TITLE
cabal-docspec | Failure on missing `/user/.cabal/config`

### ISSUE THREAD

**Issue by 4TT1L4** [phadej/cabal-extras#137]
**Problem:**
 - The `cabal-docspec` call is failing on start, when the `/user/.cabal/config` file is missing.

```
+ ./cabal-docspec
[   0.00001] ghc.info: ghc
[   0.00096] process.0.start: cwd=/tmp ghc --info
[   0.04209] peu.exception: SomeException
/user/.cabal/config: openBinaryFile: does not exist (No such file or directory)
```

**Proposal:**
 - Make sure that the `cabal-docspec` call won't fail when the mentioned file is missing.

**Workaround:**
 - Create an empty `/user/.cabal/config` file and observe the succesfull `./cabal-docspec` call.

**Comment by phadej** [comment]
Set `CABAL_CONFIG` environment variable to point to the `cabal.config` file. (I'm not sure where it's on your system).
