### ISSUE TITLE
cabal-docspec: CPP support broken after release cabal-docspec-0.0.0.20210111

### ISSUE THREAD

**Issue by harendra-kumar** [phadej/cabal-extras#139]
https://github.com/phadej/cabal-extras/releases/tag/cabal-docspec-0.0.0.20210111 works fine. But all the releases after that have a problem finding include files and using macros defined in cabal files based on the os. I am not able to upgrade to newer releases because of this issue.

To reproduce the issue:

```
git clone https://github.com/composewell/streamly.git
cd streamly
cabal build --project-file cabal.project.doctest streamly
cabal-docspec --timeout 60 --check-properties --property-variables xs streamly
```

```
[   0.30069] docspec.phase1: Streamly.Internal.FileSystem.Event.Linux: /home/harendra/composewell/streamly/./src/Streamly/Internal/FileSystem/Event/Linux.hs
[   0.30390] warning[-Wcpphs]: Warning: Can't find file "config.h" in directories
        /home/harendra/composewell/streamly/./src/Streamly/Internal/FileSystem/Event
        .
        /home/harendra/composewell/streamly/./src
        /home/harendra/composewell/streamly/./src/Streamly/Internal/Data/Stream
  Asked for by: /home/harendra/composewell/streamly/./src/Streamly/Internal/FileSystem/Event/Linux.hs  at line 58 col 1
[   0.30784] warning[-Wcpphs]: #warning "Disabling module Streamly.Internal.FileSystem.Event.Linux. Does not support kernels older than 2.6.36."
in /home/harendra/composewell/streamly/./src/Streamly/Internal/FileSystem/Event/Linux.hs  at line 1292 col 1
[   0.30916] docspec.phase1: Streamly.Internal.FileSystem.Event: /home/harendra/composewell/streamly/./src/Streamly/Internal/FileSystem/Event.hs
[   0.31257] peu.die: #error "FS Events not supported on this platform"
in /home/harendra/composewell/streamly/./src/Streamly/Internal/FileSystem/Event.hs  at line 63 col 1
```

It cannot find the `config.h` file which comes from the following include directive in `streamly.cabal`. Also, it cannot recognize the macro `CABAL_OS_LINUX`.

```
    include-dirs:
          src
    if os(linux)
      cpp-options:    -DCABAL_OS_LINUX
```

**Comment by phadej** [comment]
There are two issues

First one is that `-DFOO` flags were dropped, but they should behave as if `-DFOO=1` were given. That's an easy fix, I'll do it soon. (For now you could do `cpp-options: -DCABAL_OS_LINUX=1`)

---

Second issue is that apparently, `include-dirs` should also include directories in `build/`. When `Cabal` is building package it is passing:

```
-Isrc -Isrc/Streamly/Internal/Data/Stream -I/codetmp/streamly/dist-newstyle/build/x86_64-linux/ghc-8.6.5/streamly-0.10.0/build/src -I/codetmp/streamly/dist-newstyle/build/x86_64-linux/ghc-8.6.5/streamly-0.10.0/build/src/Streamly/Internal/Data/Stream
```

flags, so cpp include directories for in-source-tree and in-build-tree (where generated files are put) versions . That shouldn't be too hard to add either, but I have to check `Cabal` source how these paths are constructed

EDIT: The `dist-newstyle/build/x86_64-linux/ghc-8.6.5/streamly-0.10.0` part comes from `cabal-install`.

**Comment by harendra-kumar** [comment]
How was this was working earlier? What changed?

**Comment by phadej** [comment]
> How was this was working earlier? 

I don't remember. I do remember changing handling of `-D` flags. (Maybe i passed them as is through previously).

The includes never worked, but it's not an error, just a warning... and previously some (or any? cannot remember either) cpphs warnings weren't reported.
