### ISSUE TITLE
Obscure parse error from cabal-docspec

### ISSUE THREAD

**Issue by Kleidukos** [phadej/cabal-extras#152]
While trying to see if cabal-docspec could be used with exceptions, I have parse error:

```
❯ cabal-docspec --strip-comments --no-cabal-plan Main.hs
[   0.00001] ghc.info: ghc
[   0.00033] process.0.start: cwd=/tmp ghc --info
[   0.03235] ghc.read-package-db: /home/hecate/.ghcup/ghc/9.6.5/lib/ghc-9.6.5/lib/package.conf.d
[   0.05284] peu.die: cannot parse /home/hecate/Main.hs
```

Here is the snippet

```haskell
module Main where

-- $setup
-- >>> Data.Bifoldable

-- |
-- >>> bifoldr (flip const) (:) [] (undefined :: (Int, Word)) `seq` ()
-- ()
--
-- >>> foldr (:) [] (undefined :: (Int, Word)) `seq` ()
-- *** Exception: Prelude.undefined
main :: IO ()
main = putStrLn "test"
```

**Comment by phadej** [comment]
The `Main.hs` argument is treated as cabal file (i.e. package definition).  

Note: there is no way to run `cabal-docspec` on standalone files, only on packages: you need to compile them first.

**Comment by Kleidukos** [comment]
@phadej Ok great! :+1: Can you confirm that `cabal-docspec` can absolutely not be used with doctests that trigger `undefined`?

**Comment by phadej** [comment]
> Can you confirm that cabal-docspec can absolutely not be used with doctests that trigger undefined?

`cabal-docspec` can be used to test exceptions (which `undefined` is). But this issue isn't a reproducer of that, if expressions with  `undefined` don't work.
