### ISSUE TITLE
cabal-docspec: Hiding setup from haddock

### ISSUE THREAD

**Issue by LeventErkok** [phadej/cabal-extras#159]
I often end up putting code like this to get `cabal-docspec` to run initial code:

```
-- $setup
-- >>> -- For doctest purposes only:
-- >>> import Some.Module.I.Need.Only.For.Tests
-- >>> set -XSomeOptionIOnlyNeedForTests
```

And this works wonderfully, except they also show up in the generated haddock documentation; which is mostly noise.

Is there a way to specify `setup` code, but have haddock ignore that segment when the docs are generated?

Perhaps this is a Haddock question, but wondering if there's already a known-method to handle this.

**Comment by phadej** [comment]
Use export lists?

**Comment by LeventErkok** [comment]
I've been shying away from using those for the particular modules I'm interested in; but perhaps that's the way to go. Thanks!

**Comment by LeventErkok** [comment]
I found a workaround; putting this here in case anyone else run into it and want the same.

* Wrap the setup code in a HADDOCK define:

```haskell
{-# LANGUAGE CPP  #-}

#ifndef HADDOCK
-- $setup
-- >>> -- For doctest purposes only, ignore.
-- >>> :set -XDataKinds -XScopedTypeVariables
#endif
```

* When invoking haddock, use:

```
cabal new-haddock --haddock-option=--hyperlinked-source --haddock-option="--optghc=-DHADDOCK"
```

And voila! doc-test sees your setup, and haddock is blind to it.

**Comment by phadej** [comment]
... that workaround is however will cause recompilation, i.e. haddock won't reuse already compiled interface files.

I recommend to avoid using `-DHADDOCK` (bad practice), but rather specify export lists (which is a good practice for other reasons too).

**Comment by LeventErkok** [comment]
Recompilation is an issue indeed. Thanks for pointing that out.
