### ISSUE TITLE
Publish cabal-extras to Hackage

### ISSUE THREAD

**Issue by blackgnezdo** [phadej/cabal-extras#37]
@phadej any interest in publishing this package to Hackage? It would save me some complications when adding to OpenBSD ports. I so far avoided special cases for Haskell packages outside of Hackage.

If not, even a simple GitHub release would be an improvement over having to pin a specific commit.

**Comment by phadej** [comment]
Not currently. I on purpose don't bother with any release (or versioning) matters for these tools.

**Comment by blackgnezdo** [comment]
Fair enough.
