### ISSUE TITLE
[cabal-docspec] named chunks are ignored?

### ISSUE THREAD

**Issue by amesgen** [phadej/cabal-extras#62]
Thanks for your work on cabal-docspec, a joy to use!

I think that doctests in named chunks are ignored right now, see https://github.com/amesgen/stuff/tree/cabal-docspec-sections. To reproduce:

```
 $ git clone --single-branch --branch cabal-docspec-sections https://github.com/amesgen/stuff && cd stuff
 $ cabal build
 $ cabal-docspec
[   0.00002] ghc.info: ghc
[   0.00117] process.0.start: cwd=/tmp ghc --info
[   0.06146] docspec.component: stuff-0.1.0.0 lib
[   0.06170] docspec.phase1: MyLib: /tmp/tmp.Vp2wdVmVmn/stuff/./src/MyLib.hs
[   0.42845] docspec.phase2: MyLib
[   0.48455] doctest.summary: Examples: 1; Tried: 1; Skipped: 0; Success: 1; Errors: 0; Failures 0
[   0.48496] peu.completed: OK
```
(here with the latest binary, but also happens with current master)

The (failing) test in the named chunk

```
-- $foo
-- >>> 1 + 1
-- 3
```

seems to have been ignored.

**Comment by phadej** [comment]
Thank you for your report.

It's indeed bad I missed those. https://github.com/phadej/cabal-extras/pull/63 should fix it. I'll merge it as soon as CI passes, as it seems to fix the issue. It would be great if you could confirm it fixes for your use case too.

**Comment by amesgen** [comment]
Yup, works fine with #63, thanks!

Only thing I noted is that a reload is happening inbetween chunks (if there is more than one, unlike in my example above), so one has to e.g. import things again, but I think I like that behavior.

**Comment by phadej** [comment]
> Only thing I noted is that a reload is happening inbetween chunks (if there is more than one, unlike in my example above), so one has to e.g. import things again, but I think I like that behavior.

That is deliberate. `cabal-docspec` resets after each comment block or chunk. (It can afford it without considerable performance degradation). You can always use `$setup`.

**Comment by phadej** [comment]
Good. I'll make a binary release later today.
