### ISSUE TITLE
[cabal-docspec] Doctests on re-exports from private modules are not run

### ISSUE THREAD

**Issue by kozross** [phadej/cabal-extras#71]
I have a private module `Foo.Internal`, from which I export a function `bar`, which has documentation (and doctests). This is imported into the public module `Foo`, which re-exports `bar`. However, I find that the doctests for `foo` never execute at all when I run `cabal-docspec`.

Is this intentional? Am I missing something?

**Comment by phadej** [comment]
It's a limitation of the approach. https://github.com/phadej/cabal-extras/blame/master/cabal-docspec/MANUAL.md#L24-L27

**Comment by kozross** [comment]
Noted, thanks!
