### ISSUE TITLE
Release cabal-docspec to hackage?

### ISSUE THREAD

**Issue by ekmett** [phadej/cabal-extras#73]
As it is it is rather hard to test things in the post-"custom setup" world.

**Comment by phadej** [comment]
I'm not willing to this yet. It uses (liberary) dependencies which aren't on Hackage, and I don't want to put them on Hackage, nor bundle them into libraries in this repository.

Sorry, not yet.

**Comment by amigalemming** [comment]
You may try https://hackage.haskell.org/package/doctest-extract instead.
