### ISSUE TITLE
cabal v2-build failed - it fails to install 'network-3.1.2.1'

### ISSUE THREAD

**Issue by ltsdw** [phadej/cabal-extras#77]
```
Failed to build network-3.1.2.1. The failure occurred during the configure
step.
Build log (
.cabal/logs/ghc-8.10.4/network-3.1.2.1-d925f232bfe30f4c52bb06fb2656ff45a62084528801e8f75c8eaf5f22089ff2.log
):
Configuring network-3.1.2.1...
//tmp/peura-XXXX-1a1619393cf0f44a/dist-newstyle/tmp/src-73188/network-3.1.2.1/configure: line 560: 0: Bad file descriptor
cabal-3.4.0.0: Failed to build network-3.1.2.1 (which is required by
fake-package-0). See the build log above for details.

[  88.21558] process.1.time: 88.099 seconds
[  88.21653] error: ERROR: cabal v2-build failed
[  88.21680] error: This is might be due inconsistent dependencies (delete package env file, or try -a) or something else
```

It isn't a big deal, as I can simply run `cabal install --lib network-3.1.2.1` and everything will follow as normal, but I though maybe I should report it anyway.

And maybe this issue isn't even valid, as what I can see `line 560: 0: Bad file descriptor
cabal-3.4.0.0: Failed to build network-3.1.2.1`, maybe it is exclusively happening only in this package, if so please close it.

**Comment by phadej** [comment]
What does `.cabal/logs/ghc-8.10.4/network-3.1.2.1-d925f232bfe30f4c52bb06fb2656ff45a62084528801e8f75c8eaf5f22089ff2.log` say?

**Comment by ltsdw** [comment]
here network-3.1.2.1-d925f232bfe30f4c52bb06fb2656ff45a62084528801e8f75c8eaf5f22089ff2.log:
[log.txt](https://github.com/phadej/cabal-extras/files/6030119/log.txt)

**Comment by phadej** [comment]
I guess you did `cabal install --lib network-3.1.2.1` (or something) which overwrote that log, there is no error there.

Sorry, I cannot help you then.

**Comment by ltsdw** [comment]
Oh sorry about that, I'll try to reproduce it then without doing cabal install --lib

**Comment by ltsdw** [comment]
Ok, here is what I got in the entire file but I don't think it helps though...:

```
Configuring network-3.1.2.1...
//tmp/peura-XXXX-ae6d1c6533e97cc3/dist-newstyle/tmp/src-172258/network-3.1.2.1/configure: line 560: 0: Bad file descriptor
```

**Comment by phadej** [comment]
Do you use windows? is this WSL or cygwin or something?

I can find https://help.appveyor.com/discussions/problems/4150-0-bad-file-descriptor-error-running-configure

**Comment by ltsdw** [comment]
Nope, I'm running arch-linux x86_64

**Comment by phadej** [comment]
I see.

It seems I can reproduce this. The `network` shouldn't exist in cabal store, so it is built and output (of `configure` script) is passed to the output. And then it breaks.

Interesting.

**Comment by phadej** [comment]
I pushed a fix which seems to solve it for my reproducer.
