### ISSUE TITLE
rejecting: semialign-1.1.0.1 (conflict: cabal-diff => semialign^>=1.2)

### ISSUE THREAD

**Issue by ltsdw** [phadej/cabal-extras#80]
I already had installed cabal-env and when trying to recompile it I'm facing some difficulties due some dependencies issues and I don't know how to solve them.

```
cabal-3.4.0.0: Could not resolve dependencies:
[__0] trying: cabal-diff-0.1 (user goal)
[__1] next goal: semialign (dependency of cabal-diff)
[__1] rejecting: semialign-1.1.0.1 (conflict: cabal-diff => semialign^>=1.2)
[__1] skipping: semialign-1.1, semialign-1 (has the same characteristics that
caused the previous version to fail: excluded by constraint '^>=1.2' from
'cabal-diff')
[__1] fail (backjumping, conflict set: cabal-diff, semialign)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: cabal-diff, semialign
```

What should I try? Unregister somehow the semialign or something like that before compiling the cabal-env?

**Comment by fendor** [comment]
Since cabal is not trying to use version `1.2`, maybe you have to execute `cabal update` to make cabal aware of the new package?

**Comment by ltsdw** [comment]
> Since cabal is not trying to use version `1.2`, maybe you have to execute `cabal update` to make cabal aware of the new package?

there it is, it works, thank you!
