### ISSUE TITLE
release binaries should be static

### ISSUE THREAD

**Issue by hasufell** [phadej/cabal-extras#95]
easy to do with alpine musl docker container via github workflow or such

**Comment by hasufell** [comment]
Uploaded one manually here including `plan.json`: https://downloads.haskell.org/~ghcup/unofficial-bindists/cabal-docspec/

**Comment by phadej** [comment]
is there alpine GHC with `integer-gmp` backend?

**Comment by hasufell** [comment]
> is there alpine GHC with integer-gmp backend?

Yep. It's a little bit inconsistent at times, but [9.2.1 is gmp](https://downloads.haskell.org/~ghc/9.2.1/ghc-9.2.1-x86_64-alpine3.12-linux-gmp.tar.xz).
[8.10.7 is integer-simple](https://downloads.haskell.org/ghc/8.10.7/ghc-8.10.7-x86_64-alpine3.10-linux-integer-simple.tar.xz), though. The [i386 ones I build manually](https://downloads.haskell.org/~ghcup/unofficial-bindists/ghc/8.10.7/) are gmp.

**Comment by phadej** [comment]
Is there a way to say to ghcup I'd prefer a GMP version? Or is there only one ghc version, which is either GMP or integer-simple?

**Comment by phadej** [comment]
(I actually don't care about Integer backend, but `warp` is not buildable with `integer-simple` it seems, and that makes things slightly inconvenient. Although, I'd prefer a `warp` version which doens't depend on `cryptonite` at all).

**Comment by phadej** [comment]
https://github.com/phadej/cabal-extras/releases/tag/cabal-docspec-0.0.0.20211114 asset is static

**Comment by hasufell** [comment]
> Is there a way to say to ghcup I'd prefer a GMP version? Or is there only one ghc version, which is either GMP or integer-simple?

Not directly. But you can either build in an i386 container or use `ghcup install ghc --platform i386-alpine-linux 8.10.7` and that will give you my manually built ones (which are all gmp based).

**Comment by phadej** [comment]
Sorry, I'm not touching i386 in 2021.
